---
title: Project Review 
author: Annalise Cramer
date: 4/25/25
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: Working Status Analysis of H-1B Visa Workers Using H-1B LCA Disclosure Data (2020–2024)

Name of project author(s): Yufei Wu

Name of project reviewer: Annalise Cramer


## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

I think the contextualization is very strong, I understand what the H1-B visa is and the VCA. However, I think the motivation could be emphasized a little more. It's mentioned that it's a lottery system, and the last sentence says we can learn more about H1-B status by analyzing LCA data. I think more about the importance of knowing status would help.

### Summary assessment

Some contextualization and motivation


## Question description


### Feedback and Comments

No notes, strong questions.

### Summary assessment

Question/hypotheses fully clear


## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

Source of data is clear and details about dataset are given.

### Summary assessment

Source and overall structure of data well explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

I opened the EDA files and ran them. EDA starts by exploring top answers for each variable of interest, wages standardized. I like the pink and blue plots. Variables sorted by highest wage (by median). Same analysis carried out for lowest median wage. Remote work found via difference in employer state and worksite state, interesting plot.

### Summary assessment

Essentially no weaknesses in wrangling and exploratory component


## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

The first filter in the initial analysis script generates a warning. In the full analysis, I stopped at line 131 because it was taking over 30 minutes to run (I tried a second time with no luck). I'm assuming this has to do with my laptops computing power and not with the code given everything else has run with no issues. I continued on to run the SVM which gave warnings and didn't run.

Models make sense to me, single and multivariable using random forest. I think adding a little more reasoning to the manuscript for your choice of models could be helpful. 

Overall, good with a little room for improvement.


### Summary assessment

Strong and reasonable analysis.

## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

Figures look good. This may be a personaly proference, but I think having white/clear background similar to figure 2d would make things looks even nicer, which is quick using theme_minimal or cowplot package.

Model metrics tables are clean and understandable. Figure 4 plot is great.

### Summary assessment

Results are very well presented


## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

Findings discussed and next steps listed. I think only examining such a small slice of data is a huge constraint but I understand that you're working with what you have, and I wasn't able to computationally handle things on my laptop either.

### Summary assessment

Strong, complete and clear discussion


## Further comments

After reviewing everyhting, I think the introduction/motivation needs the most work and the plots could look a little cleaner. I don't think the tables need and adjustment.

# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

I think using clearer names than initial analysis and full analysis could be helpful, at first I didn't know if I needed to ignore the inital analysis or not. Maybe analysis1 and analysis2? Or clarify what they do in the readme? Everything else was well structued, all the readmes were good, the many figures and tables named in a organized manner.

### Summary assessment

Well structured


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

Adding a little but of motivation onto why you choose advanced models that you did would help me understand. Code was well commented and oragnized.

### Summary assessment

Decently documented with some gaps



## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

Warnings were coming up for SVM and I wasn't able to continue/ignore them. I couldn't get results for that section of the analysis.

I'm not going to count my laptop being unable to handle the xgboost section because that was on my end.

### Summary assessment

Small parts not reproducible or required manual intervention 



## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

Explored multiple machine learning models after exploring single models. 

### Summary assessment

Strong level of thorougness


## Further comments

I think this project is in great shape. After these few relatively small tweaks you should be good to go :)





